[project]
name = "asazuke"
version = "0.0.1"
authors = [{name="birthggd"}]
classifiers = [
    "License :: OSI Approved :: Boost Software License 1.0 (BSL-1.0)"
]

[project.urls]
homepage =  "https://github.com/bggd/asazuke"
