# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asazuke.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rasazuke.proto\"A\n\x06Object\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x11library_file_path\x18\x02 \x01(\t\x12\x0e\n\x06parent\x18\x03 \x01(\x05\"e\n\nCollection\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x11library_file_path\x18\x02 \x01(\t\x12\x1d\n\x08\x63hildren\x18\x03 \x03(\x0b\x32\x0b.Collection\x12\x0f\n\x07objects\x18\x04 \x03(\x05\"6\n\x05Scene\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1f\n\ncollection\x18\x02 \x01(\x0b\x32\x0b.Collection\";\n\x07\x41sazuke\x12\x16\n\x06scenes\x18\x01 \x03(\x0b\x32\x06.Scene\x12\x18\n\x07objects\x18\x02 \x03(\x0b\x32\x07.Objectb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asazuke_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OBJECT']._serialized_start=17
  _globals['_OBJECT']._serialized_end=82
  _globals['_COLLECTION']._serialized_start=84
  _globals['_COLLECTION']._serialized_end=185
  _globals['_SCENE']._serialized_start=187
  _globals['_SCENE']._serialized_end=241
  _globals['_ASAZUKE']._serialized_start=243
  _globals['_ASAZUKE']._serialized_end=302
# @@protoc_insertion_point(module_scope)
